# aws:
#   regions: []
#   account_id:
#   account_name:
#   profile:
  
resources:
    EBS:
      cloudwatch_metrics_days: 10
    EC2:
      avgCpu: 80
    LB:
      connectionCount: 10000 


config:
  env:
    channel_name: test  
