
##Uncomment the block and modify the defalt values


# resources:
#     EBS:
#       unused: 0    #submission of DiskWriteOps and DiskReadOps
#       cloudwatch_metrics_days: 14
#       cloudwatch_metrics_period: 1209600
    
#     EC2:
#       avgCpu: 1
#       maxCpu: 1
#       netInOut: 5000
#       cloudwatch_metrics_days: 14
#       cloudwatch_metrics_period: 1209600
    
#     ELASTICSEARCH:
#       sumCacheHitMiss: 0 #Submission of Cache Hit and Miss
#       cloudwatch_metrics_days: 14
#       cloudwatch_metrics_period: 1209600

#     ELASTICACHE:
#       sumCacheHitMiss: 0 #Submission of Cache Hit and Miss
#       cloudwatch_metrics_days: 14
#       cloudwatch_metrics_period: 1209600
      
#     LB:
#       connectionCount: 1 
#       cloudwatch_metrics_days: 14
#       cloudwatch_metrics_period: 1209600
    
#     RDS:
#       connectionCount: 0
#       cloudwatch_metrics_days: 14
#       cloudwatch_metrics_period: 1209600
    
#     REDSHIFT:
#       dbConnectionCount: 0
#       cloudwatch_metrics_days: 14
#       cloudwatch_metrics_period: 1209600
    
# config:
#   env:
#     channel_name: '-'             #Slack Channel Name
#     slack_token: '-'                   #Slack Channel Token
#     from_address: '-'                #SES verified email address from which email is to be sent
#     to_address: '-'         #Email addresses of recipents (Comma Separated)
#     ses_region: '-'                    #Region where SES is configured
#     reporting_platform: '-'    #Email/Slack/Email and Slack
#     account_name: 'AWS Account'
    
