# aws:
#   regions: []
#   account_id:
#   account_name:
#   profile:
  
resources:
  - ebs:
      enable: true #by default true
      cloudwatch_metrics_days: 
      cloudwatch_metrics_period:

  - lb:
      enable: true #by default true
      cloudwatch_metrics_days:
      cloudwatch_metrics_period: 

  - rds:
      enable: true #by default true
      cloudwatch_metrics_days:
      cloudwatch_metrics_period:

  - ec2:
      enable: true #by default true
      cloudwatch_metrics_days:
      cloudwatch_metrics_period:


