# aws:
#   regions: []
#   account_id:
#   account_name:
#   profile:
  
resources:
    ebs:
      cloudwatch_metrics_days: 100


config:
  channel_name: !ENV ${channel_name}             #Slack Channel Name
