### Default metric value to identity a idle resource
resources:
  - ebs:
      unused: 0    #submission of DiskWriteOps and DiskReadOps
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600

  - ec2:
      avgCpu: 1
      maxCpu: 1
      netInOut: 5000
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600

  - elasticCache:
      sumCacheHitMiss: 0 #Submission of Cache Hit and Miss
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600

  - lb:
      connectionCount: 1 
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600

  - rds:
      connectionCount: 1
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600

  - redshift:
      dbConnectionCount: 1
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600
    